### ISSUE TITLE
duplicate papers

### ISSUE THREAD

**Issue by zzzzzzzzzzzx** [iCGY96/awesome_OpenSetRecognition_list#13]
In open set domain adaptation 2020, the paper 'Open Set Domain Adaptation with Multi-Classifier Adversarial Network' and the last one 'Adversarial Network with Multiple Classifiers for Open Set Domain Adaptation' is the same one with different versions. Maybe you can delete one of them.  :）

**Comment by iCGY96** [comment]
I have updated our repository. Thanks for your contribution!
