### ISSUE TITLE
Code Available 

### ISSUE THREAD

**Issue by rinkita22** [iCGY96/awesome_OpenSetRecognition_list#2]
Code is available for the paper : "Open Set Recognition Through Deep Neural Network Uncertainty
: Does Out-of-Distribution Detection Require Generative Classifiers?" under this link :
https://github.com/MrtnMndt/Deep_Openset_Recognition_through_Uncertainty

**Comment by iCGY96** [comment]
Thank you for your contribution!

**Comment by Cogito2012** [comment]
@iCGY96 Hi Guangyao, the code is available for the ICCV 2021 paper: "Evidential Deep Learning for Open Set Action Recognition", where the link is [https://github.com/Cogito2012/DEAR](https://github.com/Cogito2012/DEAR). This is a great repo, thanks!

**Comment by iCGY96** [comment]
Thank you for your contribution! The code link has been added.
