### ISSUE TITLE
Paper Recommendation: TPAMI 2022

### ISSUE THREAD

**Issue by wangyuTJU** [iCGY96/awesome_OpenSetRecognition_list#29]
I have followed and starred your list for a long time. Many thanks for keeping it up to date. Recently, I strongly recommend a recent paper in TPAMI 2022, which designs a general framework for the OSR problem. The information is listed as follows.

Class-specific semantic reconstruction for open set recognition. Hongzhi Huang, Yu Wang, Qinghua Hu, Ming-Ming Cheng. IEEE Transactions on Pattern Analysis and Machine Intelligence (2022).

Paper link: https://arxiv.org/pdf/2207.02158.pdf
Code link: https://github.com/xyzedd/CSSR

**Comment by iCGY96** [comment]
Thanks for your contributions!
