### ISSUE TITLE
Request for enlisting recent journal article on open-set DA

### ISSUE THREAD

**Issue by tasfia** [iCGY96/awesome_OpenSetRecognition_list#6]
Hi,

The repository is very impressive. Can you please add my new IEEE Transactions on Multimedia article on open-set DA in your repository? 

Title: Adversarial Network with Multiple Classifiers for Open Set Domain Adaptation 
Authors: Tasfia Shermin, Guojun Lu, Shyh Wei Teng, Manzur Murshed, Ferdous Sohel
Publisher: IEEE TMM
Year: 2020
Code: https://github.com/tasfia/DAMC

Regards,
Tasfia

**Comment by iCGY96** [comment]
I have updated our repository. Thanks for your great work!
